import "./globals.css";
import Navber from "./component/Navber";

export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navber />
        {children}
      </body>
    </html>
  );
}